# Generated by Django 5.0.6 on 2024-05-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_note_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
    ]
